name: Deploy Foiex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./exchange-web
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foiex-frontend:latest

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./exchange-api
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foiex-backend:latest

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /home/exchange
          docker-compose pull
          docker-compose up -d
